// <auto-generated />
using Exercicios.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Exercicios.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230910205716_mudancas na model234")]
    partial class mudancasnamodel234
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Exercicios.Models.Remedio", b =>
                {
                    b.Property<int>("RemedioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CategoriaFarmacologica")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Dose")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Imagem")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NomeComercial")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PrincipioAtivo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ResumoBasico")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ViaAdministracao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("RemedioId");

                    b.ToTable("Remedioss");
                });

            modelBuilder.Entity("Exercicios.Models.SinalClinico", b =>
                {
                    b.Property<int>("SinalClinicoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("RemedioId")
                        .HasColumnType("int");

                    b.Property<string>("Sinal")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("SinalClinicoId");

                    b.HasIndex("RemedioId");

                    b.ToTable("SinaisClinicoss");
                });

            modelBuilder.Entity("Exercicios.Models.SinalClinico", b =>
                {
                    b.HasOne("Exercicios.Models.Remedio", null)
                        .WithMany("SinaisClinicos")
                        .HasForeignKey("RemedioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Exercicios.Models.Remedio", b =>
                {
                    b.Navigation("SinaisClinicos");
                });
#pragma warning restore 612, 618
        }
    }
}
